#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Live LaTeX rebuild on save.
#
# Wraps `latexmk -pvc` (its built-in polling watcher — no inotify needed) and
# prints a single-line status per build:
#
#     [14:32:07] ✓  129 pp · 5 warnings · 0 undef refs
#
# Errors are printed in full so you can see what broke. On success only the
# status line is printed; the LaTeX log is suppressed.
#
# Open rao-thesis-2026.pdf in zathura (or in emacs via pdf-tools) once — it auto-reloads
# on rebuild. `make view` will launch zathura/evince for you.
#
# Usage:
#     ./scripts/watch.sh                            # full build
#     ./scripts/watch.sh --only 00-introduction     # \includeonly speedup
#     ./scripts/watch.sh --only 00-introduction,04-conclusion
#
# With --only, the listed chapters are the only ones typeset. Other chapters
# still resolve cross-references via their .aux files (left from a previous
# full build). Run a full `make` once before using --only for the first time.
#
# Stop with Ctrl-C. The temporary _includeonly.tex is cleaned up on exit.
# -----------------------------------------------------------------------------

set -u
cd "$(dirname "$0")/.."

# ----- parse args -----
ONLY=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --only) ONLY="$2"; shift 2 ;;
    --only=*) ONLY="${1#*=}"; shift ;;
    -h|--help)
      sed -n '/^# Usage:/,/^# Stop/p' "$0" | sed 's/^# \?//'
      exit 0 ;;
    *)
      echo "watch.sh: unknown arg '$1' (try --help)" >&2
      exit 2 ;;
  esac
done

# ----- set up \includeonly if requested -----
INCLUDEONLY_FILE="_includeonly.tex"

cleanup() {
  # Remove the includeonly stub so a subsequent plain `make` rebuilds the
  # full document. Latexmk's .fls cache is left untouched.
  rm -f "$INCLUDEONLY_FILE"
  printf "\n[watch] stopped\n"
  exit 0
}
trap cleanup INT TERM

if [[ -n "$ONLY" ]]; then
  # Convert "00-introduction,04-conclusion" → comma-separated \include paths.
  list=""
  IFS=',' read -ra parts <<<"$ONLY"
  for raw in "${parts[@]}"; do
    name="${raw// /}"  # strip whitespace
    case "$name" in
      chapters/*) path="$name" ;;
      00-introduction|04-conclusion) path="chapters/$name" ;;
      *)          path="chapters/$name/chapter" ;;
    esac
    list+="${list:+,}${path}"
  done
  printf "%% Auto-generated by scripts/watch.sh — do not commit.\n\\includeonly{%s}\n" "$list" \
    > "$INCLUDEONLY_FILE"
  printf "[watch] \\includeonly{%s}\n" "$list"
  # Bump mtime so latexmk re-runs even if main.tex didn't actually change.
  touch main.tex
else
  rm -f "$INCLUDEONLY_FILE"
fi

# ----- summary script (called by latexmk after each build) -----
SUMMARY_SCRIPT="$(mktemp -t latex-watch-summary.XXXXXX.sh)"
# Extend cleanup to also remove the temp summary script.
trap 'rm -f "$INCLUDEONLY_FILE" "$SUMMARY_SCRIPT"; printf "\n[watch] stopped\n"; exit 0' INT TERM
# Belt-and-suspenders on normal exit.
trap 'rm -f "$SUMMARY_SCRIPT"' EXIT

cat >"$SUMMARY_SCRIPT" <<'SUMMARY_EOF'
#!/usr/bin/env bash
# Print one-line summary of the last latexmk build, based on rao-thesis-2026.log.
# Argument: "ok" | "fail" | "warn" (defaults to ok).
#
# Writes to /dev/tty directly so the summary survives even when the parent
# latexmk has its stdout/stderr redirected to /dev/null.
status="${1:-ok}"
log="rao-thesis-2026.log"

# All output goes to the controlling terminal if available, else stderr.
if [[ -w /dev/tty ]]; then exec >/dev/tty 2>&1
else                       exec 1>&2
fi

ts=$(date +%H:%M:%S)
case "$status" in
  ok)   icon=$'\033[32m✓\033[0m' ;;
  fail) icon=$'\033[31m✗\033[0m' ;;
  warn) icon=$'\033[33m!\033[0m' ;;
  *)    icon="·" ;;
esac

if [[ ! -f "$log" ]]; then
  printf "[%s] %s  no log file yet\n" "$ts" "$icon"
  exit 0
fi

pages=$(grep -oE 'Output written on [^ ]+ \([0-9]+ pages' "$log" \
        | tail -1 | grep -oE '[0-9]+' | tail -1)
warnings=$(grep -cE 'LaTeX Warning|Package .* Warning|Overfull \\hbox|Underfull \\hbox' "$log" 2>/dev/null || echo 0)
undef=$(grep -cE 'Reference .* undefined|Citation .* undefined' "$log" 2>/dev/null || echo 0)

warnings=${warnings//[[:space:]]/}
undef=${undef//[[:space:]]/}

# Note in the status line when \includeonly is active.
mode=""
[[ -f _includeonly.tex ]] && mode=" \033[36m[partial]\033[0m"

printf "[%s] %s  %s pp · %s warnings · %s undef refs%b\n" \
       "$ts" "$icon" "${pages:-?}" "$warnings" "$undef" "$mode"

if [[ "$status" == "fail" ]]; then
  echo
  grep -nE '^!|^.*:[0-9]+:' "$log" | head -20
  echo
fi
SUMMARY_EOF
chmod +x "$SUMMARY_SCRIPT"

printf "[watch] starting latexmk -pvc on main.tex (Ctrl-C to stop)\n"
printf "[watch] tip: open rao-thesis-2026.pdf in emacs (pdf-tools auto-reverts) or run 'make view'\n\n"

# -pvc           : preview-continuous (poll for changes, rebuild)
# -view=none     : do not spawn a PDF viewer
# -silent        : suppress most TeX chatter
# -interaction=  : no interactive prompt on error
# $success_cmd / $failure_cmd : hooks called after each build
exec latexmk \
    -pdf \
    -pvc \
    -view=none \
    -silent \
    -interaction=nonstopmode \
    -file-line-error \
    -e "\$success_cmd  = q[bash '$SUMMARY_SCRIPT' ok];" \
    -e "\$failure_cmd  = q[bash '$SUMMARY_SCRIPT' fail];" \
    -e "\$warning_cmd  = q[bash '$SUMMARY_SCRIPT' warn];" \
    main.tex >/dev/null 2>&1
